### ISSUE TITLE
Some lat long coordinate values are not being converted at all.

### ISSUE THREAD

**Issue by BernardIgiri** [codice/usng.js#13]
For all integer latitude values of -81 or less, or 85 or higher the LLtoUTM function fails to convert to UTM instead returning the string value of "undefined" and not populating the coords array.

Example code:
```JavaScript
const usngs = require('../usng');
const converter = new usngs.Converter();
let coords = [];
const returnValue = converter.LLtoUTM(-87, 74, coords);

coords.length === 0
returnValue === "undefined"

**Comment by stustison** [comment]
Closing this Issue as UPS coordinates are not supported. We would always love a PR, however, if anyone wants to add this functionality.
