### ISSUE TITLE
Incorrect coordinates in zone 18 (Washington D.C. area).

### ISSUE THREAD

**Issue by NickVarnado** [codice/usng.js#3]
I have been getting some errors around the D.C. area when converting usng to lat/long.  The conversion from usng to UTM is returning a northing that is off by 600000.

Here are some results I have been seeing:

![latlong](https://cloud.githubusercontent.com/assets/5723231/9664688/81d5e0b4-5239-11e5-977d-cc884e65f36d.png)

**Comment by stustison** [comment]
Thanks Nick, we'll take a look at it asap.

**Comment by stustison** [comment]
Just wanted to throw an update on here. This issue will be looked at in our next sprint, so you should see a bug fix within a couple weeks.
