### ISSUE TITLE
MGRS String with All Zeroes for Northing returns Non-Zero Latitude

### ISSUE THREAD

**Issue by DanielJDufour** [codice/usng.js#30]
```javascript
const { south } = converter.USNGtoLL('30NYF6799300000', false);
// south is 0.001, but should be 0
```

We have the same problem with proj4js/mgrs, which you can find noted here: https://github.com/proj4js/mgrs/issues/41

**Comment by DanielJDufour** [comment]
I discovered this issue with the code I included in the PR here: https://github.com/codice/usng.js/pull/29

**Comment by stustison** [comment]
It seems like it'd be easy enough to drop something in for this edge case. @djblue

**Comment by djblue** [comment]
@DanielJDufour The issue is related to https://github.com/codice/usng.js/blob/master/src/usng.ts#L1017-L1019. I should have a PR up soon to address this issue.
